api:
  security:
    token:
      secret: lupita-kitty-cat

logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reviewsmake
    username: reviewsmake
    password: reviewsmake
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true