services:
  spring-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/docker-banco
      SPRING_DATASOURCE_USERNAME: docker-usuario
      SPRING_DATASOURCE_PASSWORD: docker-senha
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      api.security.token.secret: lupita-kitty-cat
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: docker-senha-root
      MYSQL_DATABASE: docker-banco
      MYSQL_USER: docker-usuario
      MYSQL_PASSWORD: docker-senha
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
